version: '3'
services:
  # Postgres container
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_USERNAME=postgres
  
  #API container
  api:
    depends_on:
      - postgres
    image: linoypaul/simple_blog_api
    build:
      dockerfile: Dockerfile.prod
      context: ./
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
    ports:
      - '3000:3000'
      

