# Base Image
FROM node:16-alpine as builder

# Change workdir to '/usr/app'
WORKDIR /usr/app

# Copy package.json into the
# container
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the files
# into the container
COPY . .

#build prod files
RUN npm run build

FROM node:16-alpine
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY --from=builder /usr/app/dist .
CMD ["npm","run","serve"]

